---
- hosts: linux-server
  
  tasks:
          - name: Get date for testing purposes
            command: /bin/date
            changed_when: False
            register: date

          - debug: var={{ item }}
            with_items:
                    - date.stdout
