---
- name: win_toast example 
  hosts: itc
  tasks:
    - name:
      win_toast:
        expire: 60
        title: System Upgrade Notification
        msg: Automated upgrade about to start.  Please save your work and log off before
      async: 60
      poll: 0
