---
- name: Windows Automated Update
  hosts: dhcp
  tasks:
  - name: win_update
    win_updates:
      category_names:
      - SecurityUpdates
      - CriticalUpdates
      - UpdateRollups
    reboot: no
